const keywords: string[] = [
    "anime", "streaming", "watch", "episodes", "free", "pirated",
    "manga", "subtitles", "dubbed", "anime series", "anime movies",
    "anime community", "anime reviews", "anime recommendations", 
    "anime news", "anime trailers", "anime merchandise", "anime culture",
    "otaku", "cosplay", "fan art", "anime conventions", "anime streaming sites",
    "anime forums", "anime podcasts", "anime blogs", "anime characters",
    "anime genres", "action anime", "romance anime", "comedy anime",
    "fantasy anime", "sci-fi anime", "horror anime", "slice of life anime",
    "anime episodes list", "anime watchlist", "anime streaming platforms",
    "anime fanbase", "anime adaptations", "anime soundtracks", 
    "anime openings", "anime endings", "anime quotes", "anime trivia",
    "anime history", "anime production", "anime studios", "anime directors",
    "anime writers", "anime art style", "anime animation", "anime culture",
    "anime impact", "anime influence", "anime fandom", "anime discussions",
    "anime analysis", "anime theories", "anime recommendations", 
    "anime classics", "new anime", "upcoming anime", "popular anime",
    "hidden gems", "anime streaming quality", "anime subtitles quality",
    "anime viewing experience", "anime binge-watching", "anime marathons",
    "anime streaming apps", "anime watch parties", "anime community events",
    "anime merchandise shopping", "anime collectibles", "anime gifts",
    "anime themed parties", "anime music", "anime composers", 
    "anime voice actors", "anime character development", "anime plot twists",
    "anime endings", "anime cliffhangers", "anime fan theories",
    "anime character arcs", "anime relationships", "anime friendships",
    "anime rivalries", "anime battles", "anime powers", "anime worlds",
    "anime settings", "anime landscapes", "anime visuals", "anime storytelling",
    "anime emotional moments", "anime humor", "anime drama", "anime suspense",
    "anime thrillers", "anime mysteries", "anime adventures", "anime journeys",
    "anime life lessons", "anime quotes", "anime inspiration", "anime motivation",
    "anime nostalgia", "anime legacy", "anime impact on culture", 
    "anime in the west", "anime in the east", "anime globalization",
    "anime streaming trends", "anime fan engagement", "anime social media",
    "anime content creators", "anime influencers", "anime reviews",
    "anime ratings", "anime awards", "anime festivals", "anime showcases",
    "anime retrospectives", "anime documentaries", "anime interviews",
    "anime behind the scenes", "anime production process", "anime funding",
    "anime crowdfunding", "anime kickstarter", "anime fan projects",
    "anime collaborations", "anime crossovers", "anime spin-offs",
    "anime sequels", "anime reboots", "anime adaptations", "anime remakes",
    "anime live-action adaptations", "anime video games", "anime merchandise",
    "anime collectibles", "anime art books", "anime soundtracks",
    "anime themed cafes", "anime themed restaurants", "anime themed hotels",
    "anime themed events", "anime themed merchandise", "anime themed experiences",
    "no ads", "user-friendly", "clean interface", "easy navigation",
    "streaming quality", "high definition", "ad-free experience", 
    "fast loading", "seamless streaming", "content variety", "user engagement",
    "community feedback", "interactive features", "personalized content",
    "content discovery", "free access", "online entertainment", "digital media"
]

export default keywords;